# Generated by Django 3.2.11 on 2023-06-18 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_post_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100)),
                ('post_user_email', models.CharField(max_length=100)),
                ('posted_user_contact_details', models.CharField(max_length=30)),
                ('post_address', models.CharField(max_length=200)),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 521785), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(default='temp', max_length=10000000)),
                ('user_email_id', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('Is_image_safe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='issues_raised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('breif_details', models.CharField(max_length=500)),
                ('reference_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='property_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_emailid_via_login_token', models.CharField(default='', max_length=100)),
                ('property_name', models.CharField(default=None, max_length=200)),
                ('property_type', models.CharField(max_length=200)),
                ('property_city', models.CharField(default=None, max_length=30)),
                ('property_state', models.CharField(default=None, max_length=30)),
                ('property_pincode', models.CharField(default=None, max_length=6)),
                ('property_distict', models.CharField(default='null', max_length=100)),
                ('property_floor', models.IntegerField(default=0)),
                ('monthly_rent', models.IntegerField()),
                ('house_area', models.CharField(max_length=100)),
                ('furnished_or_semi', models.CharField(default='null', max_length=100, null=True)),
                ('rooms', models.CharField(default='null', max_length=100, null=True)),
                ('appliance_TV', models.BooleanField(default=False)),
                ('appliance_Fridge', models.BooleanField(default=False)),
                ('appliance_sofa', models.BooleanField(default=False)),
                ('appliance_bed', models.BooleanField(default=False)),
                ('appliance_dresser', models.BooleanField(default=False)),
                ('appliance_AC', models.BooleanField(default=False)),
                ('appliance_washing_machine', models.BooleanField(default=False)),
                ('appliance_water_heaters', models.BooleanField(default=False)),
                ('appliance_fans', models.BooleanField(default=False)),
                ('appliance_water_purifier', models.BooleanField(default=False)),
                ('appliance_tubelights', models.BooleanField(default=False)),
                ('appliance_Inventers', models.BooleanField(default=False)),
                ('parking', models.CharField(default=None, max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 511692), null=True)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('post_expire_date', models.DateTimeField(default=datetime.datetime(2023, 7, 18, 17, 41, 42, 511692))),
                ('ad_posted_by', models.CharField(default='user', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_visited_ip_address', models.CharField(default=None, max_length=100, null=True)),
                ('visted_count', models.IntegerField(default=0, max_length=1000)),
                ('visited_product_pg', models.BooleanField(default=False)),
                ('visited_profile_pg', models.BooleanField(default=False)),
                ('visited_sell_pg', models.BooleanField(default=False)),
                ('visited_plan_pg', models.BooleanField(default=False)),
                ('visited_liked_pg', models.BooleanField(default=False)),
                ('visited_help_and_support_pg', models.BooleanField(default=False)),
                ('visited_update_property_pg', models.BooleanField(default=False)),
                ('visted_time', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 521785))),
                ('active_time', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 521785))),
                ('user_state_by_geo_loc', models.CharField(default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('user_email', models.CharField(default='', max_length=50)),
                ('liked_property_ids', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(default=None, max_length=100)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=100, null=True)),
                ('last_name', models.CharField(default=None, max_length=100, null=True)),
                ('email_id', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=12)),
                ('Bio', models.CharField(default='Never Loose Hope !!', max_length=200)),
                ('user_profile_pic', models.ImageField(default=None, null=True, upload_to='')),
                ('user_password', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 511692), null=True)),
                ('no_of_requests_to_view_contact_no', models.IntegerField(default=0)),
                ('no_of_free_ad_posted_count', models.IntegerField(default=0)),
                ('no_of_paid_ad_posted_count', models.IntegerField(default=0)),
                ('user_ad_posting_enrolled', models.BooleanField(default=False)),
                ('user_ad_posting_enrolled_limit', models.IntegerField(default=0)),
                ('user_ad_posting_enrolled_limit_expired_date', models.DateField(null=True)),
                ('user_view_contact_enrolled', models.BooleanField(default=False)),
                ('user_state_by_geo_loc', models.CharField(default='null', max_length=100)),
                ('role', models.CharField(default='user', max_length=50)),
                ('user_added_by_admin', models.CharField(default=None, max_length=100, null=True)),
                ('user_platform', models.TextField(default='WEB', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users_credentials_IPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email_id', models.CharField(max_length=50)),
                ('user_ip_address', models.CharField(default=None, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 519749))),
                ('user_state_by_geo_loc', models.CharField(default='null', max_length=100)),
                ('user_coordinates', models.TextField(default=None, null=True)),
                ('user_token', models.CharField(default=None, max_length=100, null=True)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rental_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='users_credentials_app_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email_id', models.CharField(max_length=50)),
                ('user_ip_address', models.CharField(default=None, max_length=100, null=True)),
                ('user_token', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 521785))),
                ('user_state_by_geo_loc', models.CharField(default='null', max_length=100)),
                ('user_mobile_data', models.TextField(default=None, null=True)),
                ('user_coordinates', models.TextField(default=None, null=True)),
                ('user_mobile_num', models.IntegerField(default=None, null=True)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rental_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='user_id_for_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_app.property_details')),
            ],
        ),
        migrations.CreateModel(
            name='user_free_limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_contact_no_for_product_id_is', models.IntegerField(default=0)),
                ('unlocked_at', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 521785), null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.property_details')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='unsafe_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsafe_img', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 519749))),
                ('unsafe_reason', models.TextField(default='none', max_length=500)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.images')),
            ],
        ),
        migrations.CreateModel(
            name='super_Admin_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_At', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 521785), null=True)),
                ('role', models.CharField(default=None, max_length=50)),
                ('last_login_time', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 521785), null=True)),
                ('user_ip_address', models.CharField(default=None, max_length=100, null=True)),
                ('user_location', models.CharField(default=None, max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='send_text_to_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_user_id', models.IntegerField(default=0)),
                ('request_user_time', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 511692))),
                ('request_property_id', models.IntegerField(default=0)),
                ('request_user_mobile_no', models.CharField(default=0, max_length=12)),
                ('request_user_email_id', models.CharField(max_length=200)),
                ('receiver_user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rental_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='razorpay_payment_order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=500)),
                ('plan_amount', models.IntegerField()),
                ('plan_id', models.CharField(max_length=100)),
                ('created_At', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 521785), null=True)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='failure_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_message', models.TextField(default='None', max_length=2000)),
                ('created_At', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 521785), null=True)),
                ('other_responses', models.TextField(default='none', max_length=2000)),
                ('failure_user_details', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='rental_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='ad_posting_payments_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=500)),
                ('razorpay_order_id', models.CharField(max_length=500)),
                ('plan_amount', models.IntegerField()),
                ('plan_id', models.CharField(max_length=100)),
                ('created_At', models.DateTimeField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 521785), null=True)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='ad_posted_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_posted_ad_property_id', models.IntegerField(default=0)),
                ('user_posted_date', models.DateField(default=datetime.datetime(2023, 6, 18, 17, 41, 42, 521785), null=True)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.users')),
            ],
        ),
    ]
